blank_issues_enabled: true

contact_links:
  - name: Have a question? 🤔
    url: https://github.com/EvoFrame/.github/discussions
    about: Have question about this repo you think we can answer? Try a discussion thread!
